import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { Activity, AlertTriangle, Battery, Bot, CheckCircle2, ChevronRight, CircleDot, Cpu, Download, Flame, Gauge, Grid3X3, History, Home as HomeIcon, Info, Layers3, Map as MapIcon, Menu, Pause, Play, Radio, RefreshCw, Route, Satellite, Search, Settings, ShieldCheck, Signal, SlidersHorizontal, Thermometer, Wifi, WifiOff, X, Zap } from 'lucide-react'
import './App.css'

type Source='REAL'|'CALCULATED'|'ESTIMATED'|'SIMULATION'|'OFFLINE/REPLAY'
type Mode='LIVE HARDWARE'|'SIMULATION'|'REPLAY'
type Conn='DISCONNECTED'|'SCANNING'|'CONNECTING'|'CONNECTED'|'DEGRADED'|'CONNECTION LOST'
type Page='Home'|'Live Map'|'3D Digital Twin'|'Events'|'Incident Command'|'Robot Control'|'Sentinel Network'|'Hardware Center'|'Simulation Lab'|'Analytics'|'Research Mode'|'System Health'|'Calibration'|'Data History'|'Settings'|'About'
type Telemetry={type:'sentinel_telemetry';deviceId:string;timestamp:number;temperature:number;humidity:number;smoke:number;flame:boolean;battery:number;signal:number;quality?:number}
type Sentinel={id:string;x:number;y:number;baseline:{temperature:number;humidity:number;smoke:number};telemetry?:Telemetry;health:'ONLINE'|'DEGRADED'|'OFFLINE';source:Source}
type Robot={x:number;y:number;battery:number;mission:string;connected:boolean;motor:'READY'|'MOVING'|'STOPPED';obstacle:boolean;ack:string;source:Source}
type Evidence={label:string;points:number;detail:string}
type Analysis={state:string;confidence:number;x:number;y:number;uncertainty:number;support:string[];evidence:Evidence[]}
type BleCharacteristic={startNotifications:()=>Promise<void>;addEventListener:(type:string,fn:(e:Event)=>void)=>void;writeValue:(v:ArrayBuffer)=>Promise<void>}
type BluetoothDevice={name?:string;gatt?:{connect:()=>Promise<{getPrimaryService:(u:string)=>Promise<{getCharacteristic:(u:string)=>Promise<BleCharacteristic>}>}>};addEventListener?:(t:string,fn:()=>void)=>void}

const UUID={service:'7b6f0001-6d1e-4e5a-9a31-464952452d01',telemetry:'7b6f0002-6d1e-4e5a-9a31-464952452d01',command:'7b6f0003-6d1e-4e5a-9a31-464952452d01'}
const initial:Sentinel[]=[
{id:'S01',x:2,y:3,baseline:{temperature:29,humidity:68,smoke:8},health:'OFFLINE',source:'REAL'},
{id:'S02',x:8,y:3,baseline:{temperature:30,humidity:64,smoke:9},health:'OFFLINE',source:'REAL'},
{id:'S03',x:15,y:4,baseline:{temperature:30,humidity:62,smoke:10},health:'OFFLINE',source:'REAL'},
{id:'S04',x:4,y:13,baseline:{temperature:29,humidity:71,smoke:7},health:'OFFLINE',source:'REAL'},
{id:'S05',x:10,y:12,baseline:{temperature:30,humidity:63,smoke:10},health:'OFFLINE',source:'REAL'},
{id:'S06',x:17,y:14,baseline:{temperature:30,humidity:66,smoke:8},health:'OFFLINE',source:'REAL'}]
const pages:Page[]=['Home','Live Map','3D Digital Twin','Events','Incident Command','Robot Control','Sentinel Network','Hardware Center','Simulation Lab','Analytics','Research Mode','System Health','Calibration','Data History','Settings','About']
const iconMap:Record<Page,(p:{size?:number})=>JSX.Element>={Home:HomeIcon,'Live Map':MapIcon,'3D Digital Twin':Grid3X3,Events:AlertTriangle,'Incident Command':ShieldCheck,'Robot Control':Bot,'Sentinel Network':Satellite,'Hardware Center':Cpu,'Simulation Lab':Activity,Analytics:Layers3,'Research Mode':Search,'System Health':Radio,Calibration:SlidersHorizontal,'Data History':History,Settings:Settings,About:Info}
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n))
const risk=(s:Sentinel)=>{const t=s.telemetry;if(!t)return 0;return clamp((t.temperature-s.baseline.temperature)*9+Math.max(0,s.baseline.humidity-t.humidity)*.8+Math.max(0,t.smoke-s.baseline.smoke)*1.8+(t.flame?32:0),0,100)}
function analyse(ss:Sentinel[]):Analysis{const rs=ss.map(risk),support=ss.filter(s=>risk(s)>=30).map(s=>s.id),max=Math.max(0,...rs);let state='NORMAL';if(max>=15)state='ENVIRONMENTAL ANOMALY';if(max>=30&&support.length<2)state='SUSPICIOUS EVENT';if(max>=30&&support.length>=2)state='CORROBORATED EVENT';if(max>=55)state='PROBABLE FIRE EVENT';if(max>=72)state='LOCALIZED EVENT';const w=rs.map(v=>Math.max(.01,v)),sum=w.reduce((a,b)=>a+b,0);const x=ss.reduce((a,s,i)=>a+s.x*w[i],0)/sum,y=ss.reduce((a,s,i)=>a+s.y*w[i],0)/sum;const ta=Math.max(0,...ss.map(s=>s.telemetry?s.telemetry.temperature-s.baseline.temperature:0)),ha=Math.max(0,...ss.map(s=>s.telemetry?s.baseline.humidity-s.telemetry.humidity:0)),sa=Math.max(0,...ss.map(s=>s.telemetry?s.telemetry.smoke-s.baseline.smoke:0));const evidence:Evidence[]=[{label:'Temperature anomaly',points:clamp(Math.round(ta*3),0,18),detail:`Peak +${ta.toFixed(1)}°C vs local baseline`},{label:'Humidity anomaly',points:clamp(Math.round(ha*.9),0,12),detail:`Peak −${ha.toFixed(1)}% RH vs baseline`},{label:'Smoke anomaly',points:clamp(Math.round(sa*.65),0,20),detail:`Peak +${sa.toFixed(0)} index points`},{label:'Neighbour confirmation',points:clamp(support.length*5,0,15),detail:`${support.length} supporting node(s)`},{label:'Persistence / consistency',points:support.length>=2?10:0,detail:support.length>=2?'Multiple observations agree':'Not established'},{label:'Sensor reliability',points:ss.filter(s=>s.health!=='OFFLINE').length,detail:'Based on node availability'}];return{state,confidence:clamp(evidence.reduce((a,e)=>a+e.points,0),0,100),x,y,uncertainty:clamp(8.5-support.length*.75-max*.045,2.2,8.5),support,evidence}}
function Metric({label,value,source}:{label:string;value:string;source:Source}){return <div className="metric"><div><span>{label}</span><small>{source}</small></div><b>{value}</b></div>}
function Panel({title,icon,children}:{title:string;icon?:ReactNode;children:ReactNode}){return <div className="panel"><div className="panelTitle"><h2>{icon}{title}</h2></div>{children}</div>}
function Stat({icon,label,value,source}:{icon:ReactNode;label:string;value:string;source:Source}){return <div className="stat"><div className="statIcon">{icon}</div><div><small>{label}</small><strong>{value}</strong><em>{source}</em></div></div>}
function ForestMap({ss,robot,event,selected,onSelect}:{ss:Sentinel[];robot:Robot;event:Analysis;selected:string|null;onSelect:(id:string)=>void}){return <div className="forestMap"><div className="mapLegend"><span>● SENTINEL</span><span>◆ ESTIMATED EVENT</span><span>■ ROBOT</span></div>{Array.from({length:16},(_,i)=><div className="sector" key={i}>B{i+1}</div>)}{ss.map(s=><button key={s.id} className={`mapNode ${risk(s)>50?'risk':''} ${selected===s.id?'selected':''}`} style={{left:`${s.x/20*100}%`,top:`${s.y/20*100}%`}} onClick={()=>onSelect(s.id)}>{s.id.slice(1)}</button>)}<div className="uncertainty" style={{left:`${event.x/20*100}%`,top:`${event.y/20*100}%`,width:`${event.uncertainty/20*200}%`,height:`${event.uncertainty/20*200}%`}}/><div className="eventPin" style={{left:`${event.x/20*100}%`,top:`${event.y/20*100}%`}}><Flame size={15}/></div><div className="robotPin" style={{left:`${robot.x/20*100}%`,top:`${robot.y/20*100}%`}}><Bot size={15}/></div><div className="mapAxes"><span>0m</span><span>10m</span><span>20m</span></div></div>}
function Slider({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <label className="slider"><span>{label}<b>{value}</b></span><input type="range" min="0" max="100" value={value} onChange={e=>set(Number(e.target.value))}/></label>}

export default function App(){
const [page,setPage]=useState<Page>('Home'),[mode,setMode]=useState<Mode>('SIMULATION'),[running,setRunning]=useState(true),[ss,setSs]=useState(initial),[robot,setRobot]=useState<Robot>({x:10,y:18,battery:100,mission:'STANDBY',connected:false,motor:'READY',obstacle:false,ack:'NO COMMAND SENT',source:'SIMULATION'}),[gateway,setGateway]=useState<Conn>('DISCONNECTED'),[toast,setToast]=useState(''),[selected,setSelected]=useState<string|null>(null),[intensity,setIntensity]=useState(0),[wind,setWind]=useState(28),[dryness,setDryness]=useState(38),[fail,setFail]=useState(''),[weak,setWeak]=useState(''),[records,setRecords]=useState<Record<string,unknown>[]>(()=>{try{return JSON.parse(localStorage.getItem('fire-echo-records')||'[]')}catch{return[]}}),[cal,setCal]=useState({temperature:0,humidity:0,smoke:0}),[demo,setDemo]=useState(0)
const cmd=useRef<BleCharacteristic|null>(null),event=useMemo(()=>analyse(ss),[ss])
const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),2500)}
useEffect(()=>{try{localStorage.setItem('fire-echo-records',JSON.stringify(records.slice(-500)))}catch{}},[records])
useEffect(()=>{if(mode!=='SIMULATION'||!running)return;const timer=window.setInterval(()=>{setSs(prev=>prev.map((s,i)=>{if(fail===s.id)return{...s,health:'OFFLINE',source:'SIMULATION'};const hot=i===2||i===4,boost=hot?intensity*.09+demo*.8:0,t=clamp(s.baseline.temperature+.3+boost+Math.sin(Date.now()/1500+i)*.15,20,55),h=clamp(s.baseline.humidity-(hot?intensity*.42+demo*.7:0)+Math.sin(Date.now()/1700+i)*.1,20,90),sm=clamp(s.baseline.smoke+(hot?intensity*1.25+demo*2:0)+Math.sin(Date.now()/1200+i),0,500),tel:Telemetry={type:'sentinel_telemetry',deviceId:s.id,timestamp:Date.now(),temperature:t+cal.temperature,humidity:h+cal.humidity,smoke:sm+cal.smoke,flame:hot&&intensity>65&&demo>2,battery:Math.max(5,(s.telemetry?.battery??96)-.004),signal:weak===s.id?12:88,quality:weak===s.id?20:96};return{...s,telemetry:tel,health:weak===s.id?'DEGRADED':'ONLINE',source:'SIMULATION'}}));setRobot(r=>({...r,source:'SIMULATION',battery:Math.max(5,r.battery-.002)}))},900);return()=>clearInterval(timer)},[mode,running,intensity,cal,fail,weak,demo])
const onTelemetry=(e:Event)=>{const v=(e.target as {value?:DataView}).value;if(!v)return;try{const p=JSON.parse(new TextDecoder().decode(new Uint8Array(v.buffer,v.byteOffset,v.byteLength))) as Partial<Telemetry>&Partial<Robot>;if(p.type==='sentinel_telemetry'&&typeof p.deviceId==='string'&&[p.timestamp,p.temperature,p.humidity,p.smoke,p.battery,p.signal].every(x=>typeof x==='number'&&Number.isFinite(x))){setSs(prev=>prev.map(s=>s.id===p.deviceId?{...s,telemetry:p as Telemetry,health:'ONLINE',source:'REAL'}:s));setRecords(prev=>[...prev,{timestamp:p.timestamp,deviceId:p.deviceId,temperature:p.temperature,humidity:p.humidity,smoke:p.smoke,battery:p.battery,signal:p.signal,source:'REAL'}])}else if(p.type==='robot_telemetry'){setRobot(r=>({...r,...p,connected:true,source:'REAL'} as Robot))}}catch{notify('Malformed telemetry rejected.')}}
const connect=async()=>{const bt=(navigator as Navigator&{bluetooth?:{requestDevice:(o:unknown)=>Promise<BluetoothDevice>}}).bluetooth;if(!bt){notify('Hardware communication is unavailable in this browser.');return}try{setGateway('SCANNING');const d=await bt.requestDevice({filters:[{services:[UUID.service]}],optionalServices:[UUID.service]});setGateway('CONNECTING');const server=await d.gatt?.connect();if(!server)throw new Error('GATT unavailable');const service=await server.getPrimaryService(UUID.service);const tele=await service.getCharacteristic(UUID.telemetry);cmd.current=await service.getCharacteristic(UUID.command);await tele.startNotifications();tele.addEventListener('characteristicvaluechanged',onTelemetry);d.addEventListener?.('gattserverdisconnected',()=>{setGateway('CONNECTION LOST');setSs(p=>p.map(s=>({...s,health:'OFFLINE',source:'REAL'})));notify('Gateway disconnected.')});setGateway('CONNECTED');setMode('LIVE HARDWARE');notify(`Connected: ${d.name||'FIRE-ECHO gateway'}`)}catch(e){setGateway('DISCONNECTED');notify(e instanceof Error?e.message:'BLE connection failed or cancelled.')}}
const send=async(command:string,target?:{x:number;y:number})=>{if(mode!=='LIVE HARDWARE'||gateway!=='CONNECTED'||!cmd.current){notify('Command not sent: physical gateway is not connected.');return}try{await cmd.current.writeValue(new TextEncoder().encode(JSON.stringify({type:'robot_command',command,...target?{target}:{}})).buffer);setRobot(r=>({...r,ack:'WAITING FOR REAL ACK'}));notify(`Command transmitted: ${command}`)}catch{notify('Command transmission failed.')}}
const dispatch=()=>{if(mode==='SIMULATION'){setRobot(r=>({...r,mission:`VERIFY ${event.x.toFixed(1)},${event.y.toFixed(1)}`,ack:'SIMULATION ACK'}));notify('Simulation mission queued.');setDemo(Math.max(demo,6))}else void send('START_MISSION',{x:event.x,y:event.y})}
const reset=()=>{setSs(initial);setIntensity(0);setDemo(0);setRobot(r=>({...r,x:10,y:18,mission:'STANDBY',ack:'NO COMMAND SENT'}));notify('Simulation reset.')}
const exportData=(kind:'csv'|'json')=>{const data=kind==='json'?JSON.stringify(records,null,2):['timestamp,deviceId,temperature,humidity,smoke,battery,signal,source',...records.map(r=>Object.values(r).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data]));a.download=`fire-echo.${kind}`;a.click();notify(`Exported ${records.length} record(s).`)}
const source:Source=mode==='LIVE HARDWARE'?'REAL':mode==='REPLAY'?'OFFLINE/REPLAY':'SIMULATION',online=ss.filter(s=>s.health==='ONLINE').length,map=<ForestMap ss={ss} robot={robot} event={event} selected={selected} onSelect={setSelected}/>
return <div className="app"><header className="topbar"><button className="mobileMenu" onClick={()=>document.querySelector('.sidebar')?.classList.toggle('open')}><Menu/></button><div className="brand"><span className="brandMark"><Flame size={20}/></span>FIRE-ECHO <em>2.0</em></div><div className="topState"><i className={event.state==='NORMAL'?'safe':''}/>{event.state}<b>{event.confidence}%</b></div><div className="modeSwitch">{(['LIVE HARDWARE','SIMULATION','REPLAY'] as Mode[]).map(m=><button key={m} className={mode===m?'selected':''} onClick={()=>{if(m==='LIVE HARDWARE'&&gateway!=='CONNECTED'){notify('Connect the real ESP32 gateway first.');return}setMode(m);if(m==='SIMULATION'){setSs(initial);setRunning(true)}}}>{m}</button>)}</div></header><aside className="sidebar"><div className="sidebarHeader">FIRE-ECHO COMMAND SYSTEM<button onClick={()=>document.querySelector('.sidebar')?.classList.remove('open')}><X/></button></div>{['COMMAND','FIELD','LAB','SYSTEM'].map(group=><div className="navGroup" key={group}><small>{group}</small>{pages.filter(p=>({Home:'COMMAND','Live Map':'COMMAND','3D Digital Twin':'COMMAND',Events:'COMMAND','Incident Command':'COMMAND','Robot Control':'FIELD','Sentinel Network':'FIELD','Hardware Center':'FIELD','Simulation Lab':'LAB',Analytics:'LAB','Research Mode':'LAB','System Health':'SYSTEM',Calibration:'SYSTEM','Data History':'SYSTEM',Settings:'SYSTEM',About:'SYSTEM'}[p])===group).map(p=>{const I=iconMap[p];return <button className={page===p?'navItem active':'navItem'} key={p} onClick={()=>{setPage(p);document.querySelector('.sidebar')?.classList.remove('open')}}><I size={17}/>{p}<ChevronRight size={13}/></button>})}</div>)}<div className="sidebarFooter"><span>GATEWAY <b>{gateway}</b></span><span>DATA <b>{source}</b></span></div></aside><main className="content"><div className="pageHeader"><div><div className="eyebrow">FIRE-ECHO / {page.toUpperCase()}</div><h1>{page}</h1><p>{desc(page)}</p></div><span className="sourceBadge"><CircleDot size={12}/> {source}</span></div>
{page==='Home'&&<><section className="statGrid"><Stat icon={<Satellite/>} label="ACTIVE SENTINELS" value={`${online}/${ss.length}`} source={source}/><Stat icon={<ShieldCheck/>} label="EVENT CONFIDENCE" value={`${event.confidence}%`} source="CALCULATED"/><Stat icon={<MapIcon/>} label="LOCALIZATION" value={`±${event.uncertainty.toFixed(1)}m`} source="ESTIMATED"/><Stat icon={<Bot/>} label="ROBOT" value={robot.mission} source={robot.source}/></section><section className="heroGrid"><div className="panel"><PanelTitle title="FOREST SITUATIONAL AWARENESS" icon={<MapIcon size={16}/>}/>{map}</div><div className="panel alertPanel"><span className="eyebrow">SYSTEM CONCLUSION</span><h2>{event.state}</h2><div className="confidenceRing"><b>{event.confidence}</b><span>RULE-BASED<br/>SCORE</span></div><button className="primary wide" disabled={event.state==='NORMAL'} onClick={dispatch}><Bot size={16}/> SEND FOR VERIFICATION</button><p className="micro">No scientifically validated fire probability is claimed.</p></div></section><section className="threeGrid"><Panel title="WHY ENGINE" icon={<ShieldCheck/>}>{event.evidence.slice(0,4).map(e=><div className="evidence" key={e.label}><span>{e.label}</span><b>+{e.points}</b></div>)}</Panel><Panel title="NETWORK HEALTH" icon={<Radio/>}><Metric label="Online nodes" value={`${online}/${ss.length}`} source="CALCULATED"/><Metric label="Gateway" value={gateway} source={gateway==='CONNECTED'?'REAL':'OFFLINE/REPLAY'}/></Panel><Panel title="OPERATOR ACTIONS" icon={<Zap/>}><button className="actionRow" onClick={()=>setPage('Live Map')}>Open map <ChevronRight/></button><button className="actionRow" onClick={()=>setPage('Hardware Center')}>Test hardware <ChevronRight/></button><button className="actionRow" onClick={()=>setPage('Simulation Lab')}>Run demo <ChevronRight/></button></Panel></section></>}
{page==='Live Map'&&<section className="workspace"><div className="panel mapLarge">{map}</div><Panel title="LOCALIZATION" icon={<MapIcon size={16}/>}><Metric label="X" value={`${event.x.toFixed(2)}m`} source="ESTIMATED"/><Metric label="Y" value={`${event.y.toFixed(2)}m`} source="ESTIMATED"/><Metric label="Uncertainty" value={`±${event.uncertainty.toFixed(2)}m`} source="ESTIMATED"/><h4>SUPPORTING NODES</h4>{event.support.length?event.support.map(id=><button className="nodeRow" key={id} onClick={()=>setSelected(id)}><Satellite size={14}/>{id}<ChevronRight/></button>):<Empty text="No corroborating nodes."/>}</Panel></section>}
{page==='3D Digital Twin'&&<section className="panel twinPanel"><div className="panelTop"><PanelTitle title="3D FOREST DIGITAL TWIN" icon={<Grid3X3 size={16}/>}/><span className="sourceBadge">{mode}</span></div><div className="twinScene">{Array.from({length:46},(_,i)=><span className="tree3d" key={i} style={{left:`${4+(i*37)%92}%`,top:`${15+(i*23)%70}%`,transform:`scale(${.55+(i%5)*.12})`}}>▲</span>)}{ss.map(s=><div className="tower3d" key={s.id} style={{left:`${s.x/20*100}%`,top:`${18+s.y/20*65}%`}}>{s.id}</div>)}<div className="event3d" style={{left:`${event.x/20*100}%`,top:`${18+event.y/20*65}%`}}><Flame/></div><div className="robot3d" style={{left:`${robot.x/20*100}%`,top:`${18+robot.y/20*65}%`}}><Bot/></div><div className="twinHud"><b>20 × 20 m</b><span>SHARED COORDINATE SPACE</span><b>{mode}</b></div></div><p className="micro">Spatial objects use the same coordinate system as the map, localization and robot mission.</p></section>}
{page==='Events'&&<section className="twoCol"><Panel title="EVENT STATE MACHINE" icon={<Route/>}>{['NORMAL','ENVIRONMENTAL ANOMALY','SUSPICIOUS EVENT','CORROBORATED EVENT','PROBABLE FIRE EVENT','LOCALIZED EVENT'].map(s=><div className={event.state===s?'stage current':'stage'} key={s}><CircleDot size={12}/>{s}</div>)}</Panel><Panel title="EVENT EVIDENCE" icon={<ShieldCheck/>}>{event.evidence.map(e=><div className="evidence" key={e.label}><div><b>{e.label}</b><span>{e.detail}</span></div><strong>+{e.points}</strong></div>)}<div className="eventTotal">CONFIDENCE <b>{event.confidence}%</b></div></Panel></section>}
{page==='Incident Command'&&<section className="panel incident"><span className="eyebrow">OPERATOR VERIFICATION</span><h2>{event.state}</h2><div className="statGrid"><Stat icon={<MapIcon/>} label="LOCATION" value={`(${event.x.toFixed(1)},${event.y.toFixed(1)})`} source="ESTIMATED"/><Stat icon={<Gauge/>} label="UNCERTAINTY" value={`±${event.uncertainty.toFixed(1)}m`} source="ESTIMATED"/><Stat icon={<ShieldCheck/>} label="CONFIDENCE" value={`${event.confidence}%`} source="CALCULATED"/></div><div className="decisionGrid"><button className="primary" onClick={dispatch}><Bot/> SEND FOR VERIFICATION</button><button className="dangerBtn" onClick={()=>void send('STOP')}><Pause/> STOP ROBOT</button><button className="ghost" onClick={()=>void send('RETURN_HOME')}><Route/> RETURN HOME</button></div></section>}
{page==='Robot Control'&&<section className="twoCol"><Panel title="ROBOT CONTROL CENTER" icon={<Bot/>}><div className="robotVisual"><Bot size={55}/></div><div className="statGrid compact"><Stat icon={<Wifi/>} label="CONNECTION" value={mode==='SIMULATION'?'SIMULATION':robot.connected?'CONNECTED':'OFFLINE'} source={robot.source}/><Stat icon={<Battery/>} label="BATTERY" value={`${robot.battery.toFixed(0)}%`} source={robot.source}/><Stat icon={<MapIcon/>} label="POSITION" value={`${robot.x.toFixed(1)}, ${robot.y.toFixed(1)}`} source={robot.source}/><Stat icon={<Signal/>} label="OBSTACLE" value={robot.obstacle?'DETECTED':'CLEAR'} source={robot.source}/></div>{['START','PAUSE','RESUME','STOP','RETURN_HOME','VERIFY_TARGET'].map(c=><button className={c==='STOP'?'dangerBtn':'ghost'} key={c} onClick={()=>c==='VERIFY_TARGET'?dispatch():void send(c)}>{c}</button>)}<div className="ack">ACK: {robot.ack}</div></Panel><Panel title="MISSION" icon={<Route/>}><Metric label="Current mission" value={robot.mission} source={robot.source}/><Metric label="Target" value={`(${event.x.toFixed(1)},${event.y.toFixed(1)})`} source="ESTIMATED"/><p className="micro">The phone sends the target; the ESP32 robot handles motors and obstacles locally.</p></Panel></section>}
{page==='Sentinel Network'&&<section className="panel"><div className="panelTop"><PanelTitle title="SENTINEL NETWORK" icon={<Satellite size={16}/>}/><span>{online}/{ss.length} ONLINE</span></div><div className="sentinelTable"><div className="tableHead"><span>NODE</span><span>STATUS</span><span>TEMP</span><span>RH</span><span>SMOKE</span><span>RISK</span><span>BATTERY</span><span>SOURCE</span></div>{ss.map(s=><button className="tableRow" key={s.id} onClick={()=>setSelected(s.id)}><b>{s.id}</b><span>{s.health}</span><span>{s.telemetry?`${s.telemetry.temperature.toFixed(1)}°C`:'—'}</span><span>{s.telemetry?`${s.telemetry.humidity.toFixed(0)}%`:'—'}</span><span>{s.telemetry?s.telemetry.smoke.toFixed(0):'—'}</span><span>{risk(s).toFixed(0)}</span><span>{s.telemetry?`${s.telemetry.battery.toFixed(0)}%`:'—'}</span><span>{s.source}</span></button>)}</div></section>}
{page==='Hardware Center'&&<section className="twoCol"><Panel title="ESP32 GATEWAY" icon={<Cpu/>}><div className="connectionHero"><Cpu size={36}/><h2>{gateway}</h2><p>Android ↔ ESP32 Gateway via BLE</p></div><button className="primary wide" onClick={connect}>{gateway==='SCANNING'?'SCANNING…':'SCAN FOR FIRE-ECHO GATEWAY'}</button><p className="micro">Only a browser-reported BLE connection can enter LIVE HARDWARE.</p></Panel><Panel title="HARDWARE TEST" icon={<CheckCircle2/>}>{['BLE connection','Gateway telemetry','Sentinel telemetry','Robot telemetry','Command channel'].map(x=><div className="testRow" key={x}><span>{x}</span><b className={gateway==='CONNECTED'?'pass':'fail'}>{gateway==='CONNECTED'?'✓ PASS':'— WAITING'}</b></div>)}</Panel></section>}
{page==='Simulation Lab'&&<section className="twoCol"><Panel title="ENVIRONMENT SIMULATION" icon={<SlidersHorizontal/>}><div className="simulationRibbon"><Zap/> SIMULATION MODE — NO HARDWARE DATA</div><Slider label="Event intensity" value={intensity} set={setIntensity}/><Slider label="Wind" value={wind} set={setWind}/><Slider label="Dryness" value={dryness} set={setDryness}/><div className="buttonLine"><button className="primary" onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}{running?'PAUSE':'RUN'}</button><button className="ghost" onClick={reset}><RefreshCw/>RESET</button></div><select value={fail} onChange={e=>setFail(e.target.value)}><option value="">No sensor failure</option>{ss.map(s=><option key={s.id} value={s.id}>{s.id} offline</option>)}</select><select value={weak} onChange={e=>setWeak(e.target.value)}><option value="">No weak link</option>{ss.map(s=><option key={s.id} value={s.id}>{s.id} weak signal</option>)}</select></Panel><Panel title="COMPETITION DEMO" icon={<Play/>}><div className="demoSteps">{['NORMAL FOREST','TEMPERATURE RISE','HUMIDITY FALL','SMOKE ANOMALY','NEIGHBOUR CONFIRMATION','EVENT LOCALIZED','ROBOT DISPATCH','ROBOT VERIFICATION'].map((x,i)=><button className={i<=demo?'demoStep done':'demoStep'} key={x} onClick={()=>{setDemo(i);setIntensity(Math.min(100,20+i*12));setRunning(true)}}>{String(i+1).padStart(2,'0')} {x}</button>)}</div><p className="micro">Safe digital demonstration only; no real flame or hazardous smoke is needed.</p></Panel></section>}
{page==='Analytics'&&<section className="panel"><div className="statGrid"><Stat icon={<Thermometer/>} label="AVG TEMP" value={`${(ss.reduce((a,s)=>a+(s.telemetry?.temperature||0),0)/Math.max(1,online)).toFixed(1)}°C`} source="CALCULATED"/><Stat icon={<Gauge/>} label="AVG RH" value={`${(ss.reduce((a,s)=>a+(s.telemetry?.humidity||0),0)/Math.max(1,online)).toFixed(1)}%`} source="CALCULATED"/><Stat icon={<Activity/>} label="RECORDS" value={`${records.length}`} source="OFFLINE/REPLAY"/><Stat icon={<ShieldCheck/>} label="SCORE" value={`${event.confidence}%`} source="CALCULATED"/></div><div className="bars">{ss.map(s=><div className="barCol" key={s.id}><b>{risk(s).toFixed(0)}</b><i style={{height:`${risk(s)}%`}}/><span>{s.id}</span></div>)}</div></section>}
{page==='Research Mode'&&<section className="twoCol"><Panel title="METHOD" icon={<Search/>}><h3>Weighted spatial estimation</h3><pre>{`wᵢ = anomaly × reliability\nx̂ = Σ(wᵢxᵢ) / Σwᵢ\nŷ = Σ(wᵢyᵢ) / Σwᵢ\nuncertainty increases when geometry is weak`}</pre><p>Local baselines and transparent rule-based evidence are used. The confidence score is not a validated fire probability.</p></Panel><Panel title="CURRENT RESULT" icon={<Info/>}><Metric label="State" value={event.state} source="CALCULATED"/><Metric label="Location" value={`(${event.x.toFixed(2)}, ${event.y.toFixed(2)})m`} source="ESTIMATED"/><Metric label="Uncertainty" value={`±${event.uncertainty.toFixed(2)}m`} source="ESTIMATED"/><Metric label="Supporting nodes" value={event.support.join(', ')||'None'} source="CALCULATED"/></Panel></section>}
{page==='System Health'&&<section className="twoCol"><Panel title="SYSTEM HEALTH" icon={<Radio/>}><Health label="Gateway" value={gateway} good={gateway==='CONNECTED'}/><Health label="Sentinels" value={`${online}/${ss.length} online`} good={online>0||mode==='SIMULATION'}/><Health label="Robot" value={mode==='SIMULATION'?'SIMULATION':robot.connected?'CONNECTED':'OFFLINE'} good={mode==='SIMULATION'||robot.connected}/><Health label="Data source" value={source} good/></Panel><Panel title="DATA QUALITY" icon={<ShieldCheck/>}><Metric label="Configured nodes" value={`${ss.length}`} source="CALCULATED"/><Metric label="Offline nodes" value={`${ss.filter(s=>s.health!=='ONLINE').length}`} source="CALCULATED"/><p className="micro">Stale or disconnected telemetry is never silently represented as live.</p></Panel></section>}
{page==='Calibration'&&<section className="twoCol"><Panel title="LOCAL OFFSETS" icon={<SlidersHorizontal/>}><label>Temperature <input type="number" value={cal.temperature} onChange={e=>setCal({...cal,temperature:Number(e.target.value)})}/></label><label>Humidity <input type="number" value={cal.humidity} onChange={e=>setCal({...cal,humidity:Number(e.target.value)})}/></label><label>Smoke <input type="number" value={cal.smoke} onChange={e=>setCal({...cal,smoke:Number(e.target.value)})}/></label><p className="micro">Stored locally. Use a trusted reference before applying offsets to real hardware.</p></Panel><Panel title="CALIBRATION RULE">Raw values are never rewritten; offsets are explicit configuration applied before the simulation's normalized telemetry.</Panel></section>}
{page==='Data History'&&<section className="panel"><div className="panelTop"><PanelTitle title="LOCAL DATA HISTORY" icon={<History size={16}/>}/><div className="buttonLine"><button className="ghost" onClick={()=>exportData('csv')}><Download/>CSV</button><button className="ghost" onClick={()=>exportData('json')}><Download/>JSON</button><button className="dangerBtn" onClick={()=>setRecords([])}>CLEAR</button></div></div>{records.length?<div className="historyTable">{records.slice(-100).reverse().map((r,i)=><div className="historyRow" key={i}>{Object.entries(r).map(([k,v])=><span key={k}>{k}: {String(v)}</span>)}</div>)}</div>:<Empty text="No stored telemetry records yet."/>}</section>}
{page==='Settings'&&<section className="twoCol"><Panel title="FOREST MODEL" icon={<Grid3X3/>}><Metric label="Width" value="20m" source="CALCULATED"/><Metric label="Height" value="20m" source="CALCULATED"/><Metric label="Origin" value="(0,0)" source="CALCULATED"/><Metric label="Sectors" value="4 × 4" source="CALCULATED"/></Panel><Panel title="OPERATING MODE" icon={<Settings/>}>{(['LIVE HARDWARE','SIMULATION','REPLAY'] as Mode[]).map(m=><button className={mode===m?'modeCard active':'modeCard'} key={m} onClick={()=>m==='LIVE HARDWARE'?void connect():setMode(m)}><b>{m}</b><span>{m==='LIVE HARDWARE'?'Only real telemetry':'Separated '+m.toLowerCase()+' data'}</span></button>)}</Panel></section>}
{page==='About'&&<section className="about"><div className="aboutHero"><div className="brandMark large"><Flame size={38}/></div><span className="eyebrow">ENVIRONMENTAL INTELLIGENCE PLATFORM</span><h2>FIRE-ECHO 2.0</h2><p>Distributed sensing • transparent fusion • spatial estimation • operator-led verification</p></div><div className="threeGrid"><Panel title="TRUTHFUL DATA" icon={<ShieldCheck/>}><p>Every value is explicitly sourced as REAL, CALCULATED, ESTIMATED, SIMULATION or OFFLINE/REPLAY.</p></Panel><Panel title="HARDWARE PATH" icon={<Cpu/>}><p>ESP32 sentinels and robot use a documented BLE service and JSON telemetry protocol.</p></Panel><Panel title="SAFE DEMO" icon={<Activity/>}><p>Competition demonstrations use digital environmental changes, not real fire.</p></Panel></div></section>}
</main>{selected&&<div className="selectionDrawer"><button onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">SELECTED NODE</span><h3>{selected}</h3>{ss.find(s=>s.id===selected)?.telemetry?<>{(()=>{const s=ss.find(x=>x.id===selected)!;const t=s.telemetry!;return <><Metric label="Temperature" value={`${t.temperature.toFixed(1)}°C`} source={s.source}/><Metric label="Humidity" value={`${t.humidity.toFixed(1)}%`} source={s.source}/><Metric label="Smoke" value={`${t.smoke.toFixed(0)}`} source={s.source}/><Metric label="Battery" value={`${t.battery.toFixed(0)}%`} source={s.source}/></>})()}</>:<Empty text="NO LIVE HARDWARE DATA"/>}</div>}{toast&&<div className="toast"><CheckCircle2 size={16}/>{toast}</div>}</div>}
function Health({label,value,good}:{label:string;value:string;good:boolean}){return <div className="healthRow"><span>{label}</span><b className={good?'pass':'fail'}>{good?'✓':'—'} {value}</b></div>}
function Empty({text}:{text:string}){return <div className="empty"><WifiOff size={18}/>{text}</div>}
function desc(p:Page){const d:Record<Page,string>={Home:'Distributed environmental intelligence command center','Live Map':'Coordinate-based localization and information gaps','3D Digital Twin':'Data-driven spatial forest model',Events:'Transparent event state machine and evidence trail','Incident Command':'Operator-led incident verification','Robot Control':'Physical verification robot command interface','Sentinel Network':'Node telemetry, baselines and health','Hardware Center':'ESP32 gateway and BLE diagnostics','Simulation Lab':'Safe simulation and what-if testing',Analytics:'Environmental trends and network analytics','Research Mode':'Methods, assumptions and mathematical transparency','System Health':'Connection and data-quality monitoring',Calibration:'Local sensor calibration offsets','Data History':'Locally stored telemetry records',Settings:'Forest model and operating mode',About:'FIRE-ECHO architecture and project information'};return d[p]}
